### ISSUE TITLE
(duplicate) Fibonacci Timeout

### ISSUE THREAD

**Issue by michaelheider** [nicdard/compiler-design-eth-tests#15] opened 2021-10-21 08:08 UTC
The Fibonacci test, calculates the 30th Fibonacci number. On our implementation, this gives sometimes a timeout (5s). Maybe lower it to Fibonacci of 20, which works more reliably.

**Comment by Bauboo** [comment] 2021-10-21 08:10
duplicate of #6

**Closed as completed by Bauboo** 2021-10-21 08:10 UTC
